### ISSUE TITLE
Incorrect import statement in README

### ISSUE THREAD

**Issue by nkmathew** [EliFinkelshteyn/alphabet-detector#5]
This doesn't work for me(currently in the reamde):

```python
from alphabet_detector import AlphabetDetector
ad = AlphabetDetector()
```

Should be this way:

```python
from alphabet_detector.alphabet_detector import AlphabetDetector
ad = AlphabetDetector()
```

**Comment by EliFinkelshteyn** [comment]
Hey @nkmathew, I just tested and verified `from alphabet_detector import AlphabetDetector` works fine. This works specifically because of the `from alphabet_detector import *` statement in __init__.py. 

Did you install with pip? If so, can you give details about what version of Python you're on?

**Comment by nkmathew** [comment]
$ python --version
    Python 3.4.3

![](http://i.imgur.com/VEEWzMD.png)

```bash
python -c "
from transliterate import detect_language, translit
from alphabet_detector.alphabet_detector import AlphabetDetector
## from alphabet_detector import AlphabetDetector

import sys

text = ''
if len(sys.argv) > 1:
  text = sys.argv[1]

ad = AlphabetDetector()

## lang = detect_language(text)
## lang = detect_language(text)
if ad.is_cyrillic(text):
  print(translit(text, 'ru', reversed=True))
else:
  print(translit(text, 'ru'))

## print(lang, sys.argv)

" "$1"
```

**Comment by EliFinkelshteyn** [comment]
Seems like they got rid of the ability to do absolute imports in `__init__.py` in (at least) later versions of Python3. Will have to switch to a relative import. Thanks for noticing this and mentioning it. Will fix soon.

**Comment by EliFinkelshteyn** [comment]
I'll push 0.0.5 with this in a bit. Before I do, mind verifying this new version has `from alphabet_detector import AlphabetDetector` working for you?

**Comment by nkmathew** [comment]
yep, it works
