### ISSUE TITLE
Does not work with Hangul

### ISSUE THREAD

**Issue by yjchua** [EliFinkelshteyn/alphabet-detector#6]
Korean Hangul characters are marked as false when is_cjk(korean_text_here) is run.

**Comment by EliFinkelshteyn** [comment]
Thanks for reporting this! Turns out Unicode has a separate class for Hangul (which makes some sense). I'll add a fix that considers that to be CJK as well.

**Comment by EliFinkelshteyn** [comment]
this is fixed by 0deaa3c96264221d1367229540f937cc95f2bb30
