### ISSUE TITLE
What CYRILLIC set is contain?

### ISSUE THREAD

**Issue by mrgloom** [EliFinkelshteyn/alphabet-detector#8]
How to obtain only russian words? Using `CYRILLIC` I also get something like `ќе` and `ївка`, etc.

**Comment by mrgloom** [comment]
Cyrilic != Russian and for russian more precise is to use `RUSSIAN_CHARS_REGEX = re.compile(u"[\u0430-\u044f\u0451\u0401\u0410-\u042f]+")` assuming `russian_alphabet = u"абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ"`

**Comment by EliFinkelshteyn** [comment]
That’s correct. This is suitable for Cyrillic in general (which would include characters from Serbian Cyrillic, for example, which are not in Russian Cyrillic). I’d be open to having a separate option for some language-specific alphabets, if there’s interest in that.

**Comment by mrgloom** [comment]
I have installed your package, following suggestion from one of the stackoverflow answers which was using plain russian string and `CYRILLIC` setting as example and it's very missleading because Cyrilic != Russian.
